# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BalanceInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, coin: str=None, amount: int=None):  # noqa: E501
        """BalanceInfo - a model defined in Swagger

        :param coin: The coin of this BalanceInfo.  # noqa: E501
        :type coin: str
        :param amount: The amount of this BalanceInfo.  # noqa: E501
        :type amount: int
        """
        self.swagger_types = {
            'coin': str,
            'amount': int
        }

        self.attribute_map = {
            'coin': 'coin',
            'amount': 'amount'
        }

        self._coin = coin
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'BalanceInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BalanceInfo of this BalanceInfo.  # noqa: E501
        :rtype: BalanceInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def coin(self) -> str:
        """Gets the coin of this BalanceInfo.

        Coin code  # noqa: E501

        :return: The coin of this BalanceInfo.
        :rtype: str
        """
        return self._coin

    @coin.setter
    def coin(self, coin: str):
        """Sets the coin of this BalanceInfo.

        Coin code  # noqa: E501

        :param coin: The coin of this BalanceInfo.
        :type coin: str
        """

        self._coin = coin

    @property
    def amount(self) -> int:
        """Gets the amount of this BalanceInfo.


        :return: The amount of this BalanceInfo.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this BalanceInfo.


        :param amount: The amount of this BalanceInfo.
        :type amount: int
        """

        self._amount = amount
