# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.balance_info import BalanceInfo
from swagger_server import util


class ExchangePingInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, item_list: List[BalanceInfo]=None):  # noqa: E501
        """ExchangePingInfo - a model defined in Swagger

        :param code: The code of this ExchangePingInfo.  # noqa: E501
        :type code: str
        :param item_list: The item_list of this ExchangePingInfo.  # noqa: E501
        :type item_list: List[BalanceInfo]
        """
        self.swagger_types = {
            'code': str,
            'item_list': List[BalanceInfo]
        }

        self.attribute_map = {
            'code': 'code',
            'item_list': 'item_list'
        }

        self._code = code
        self._item_list = item_list

    @classmethod
    def from_dict(cls, dikt) -> 'ExchangePingInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExchangePingInfo of this ExchangePingInfo.  # noqa: E501
        :rtype: ExchangePingInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this ExchangePingInfo.

        Exchange code  # noqa: E501

        :return: The code of this ExchangePingInfo.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ExchangePingInfo.

        Exchange code  # noqa: E501

        :param code: The code of this ExchangePingInfo.
        :type code: str
        """

        self._code = code

    @property
    def item_list(self) -> List[BalanceInfo]:
        """Gets the item_list of this ExchangePingInfo.


        :return: The item_list of this ExchangePingInfo.
        :rtype: List[BalanceInfo]
        """
        return self._item_list

    @item_list.setter
    def item_list(self, item_list: List[BalanceInfo]):
        """Sets the item_list of this ExchangePingInfo.


        :param item_list: The item_list of this ExchangePingInfo.
        :type item_list: List[BalanceInfo]
        """

        self._item_list = item_list
